### ISSUE TITLE
KeyError if node doesn't have any labels set

### ISSUE THREAD

**Issue by webvictim** [gravitational/rbac-linter#6]
```console
$ python3 role_query.py data/nodes.yaml data/roles.yaml
Traceback (most recent call last):
  File "/Users/gus/saleseng/rbac-linter/role_query.py", line 82, in <module>
    main()
  File "/Users/gus/saleseng/rbac-linter/role_query.py", line 70, in main
    node_matches_role(nodes, roles)
  File "/Users/gus/saleseng/rbac-linter/role_query.py", line 12, in node_matches_role
    node_labels = node['metadata']['labels']
KeyError: 'labels'

$ cat data/nodes.yaml
kind: node
metadata:
  expires: "2021-12-16T15:21:25Z"
  id: 1638972710140895259
  name: 31e62008-012f-4b65-8997-9df524b2316b
spec:
  addr: 10.10.67.28:3022
  hostname: ip-10-10-67-28-us-east-2-compute-internal
  rotation:
    current_id: 8b81073e-b474-40ea-8646-d8a66d1ee249
    grace_period: 10m0s
    last_rotated: "2021-12-03T19:43:59.014196449Z"
    phase: standby
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
    state: standby
  version: 7.3.2
version: v2
```

**Comment by ahelwer** [comment]
In what circumstances would a role allow access to a node that doesn't have any labels? Only in the case that the role allows `* : *` labels? Or is it also allowed when the role doesn't have any constraints on those labels at all?
